name: 'Sanic Actions'
description: 'GitHub Actions to Manage sanic-org repositories'
author: 'sanic-org'
inputs:
  action:
    required: false
    description: 'Kind of Operation Being Performed using the Actions. Tests/Docs/SanityCheck/Analysis'
    default: 'tests'
  test-infra-tool:
    required: false
    description: 'Name of the Test Management Infrastructure. Defaults to Tox'
    default: 'tox'
  test-infra-version:
    required: false
    description: 'Version of the Test Management infrastructure'
    default: 'latest'
  additional-test-args:
    required: false
    description: 'Additional Arguments to be passed onto the Test Infra'
    default: ''
  force-test-tool-install:
    required: false
    description: 'Force Install the Test tool even if the Env does not need it'
    default: "false"
  linter-infra-tool:
    required: false
    description: 'Tool used to perming linting operation on the repository'
    default: 'black'
  linter-infra-version:
    required: false
    description: 'Install a specific version of linter tool chain as required'
    default: 'latest'
  additional-linter-args:
    required: false
    description: 'Additional Override argument to be passed to the Linter'
    default: ''
  python-version:
    required: true
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.x'
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    required: false
  token:
    description: Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
    required: false
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
  test-infra-version:
    description: 'Currently installed version of the Test Infra Package'
  linter-infra-version:
    description: 'Version of the Linter tool configured'
runs:
  using: 'node12'
  main: 'dist/index.js'
